#!/bin/bash

oldnum=`xrandr -q | grep \ connected | wc -l`

while [ 0 ]; do

  num=`xrandr -q | grep \ connected | wc -l`

  if [ $num -ne $oldnum ]; then
    [ $num -eq 2 ] && $HOME/external
    [ $num -eq 1 ] && $HOME/internal

    oldnum=$num
  fi

  sleep 2
done
