#!/bin/bash
port=/sys/devices/*/*/drm/card*/card*/intel_backlight/brightness
while [ 0 ]; do
	read -n 1 -d '' i
	clear
	last=`cat $port`
	incr=0
	[ $i = 'u' ] && incr=1052
	[ $i = 'd' ] && incr=950
	amount=$(( last * incr / 1000 ))
  [ $i = 'u' ] && (( amount++ ))
  echo -n $amount
	echo $amount | sudo tee $port >& /dev/null
done
