#!/bin/bash

compile() {
  for i in inotify waitfor; do
    if [ ! -e bin/$i ]; then
      echo "Making $i"
      cc src/$i.c -o bin/$i
    fi
  done
}

install() {
  name=`basename $1`
  install=0
  if [ ! -e $HOME/bin/$name ]; then
    install=1
  else
    issame=`md5sum $HOME/bin/$name $1 | uniq -w 33 | wc -l`
    if [ $issame -eq "1" ]; then
      install=0
    else
      echo "The checksums for $name don't match. Do you want to install it anyway? (y/n)"
      read n
      if [ $n = "y" ]; then
        install=1
      fi
    fi
  fi

  if [ $install -eq "1" ]; then
    echo "Installing $name"
    cp -p $1 $HOME/bin
  else
    echo "Skipping $name"
  fi
}

compile

cd bin
if [ $# -gt 0 ]; then
  while [ $# -gt 0 ]; do
    install $1
    shift
  done
else
  for i in `find -maxdepth 1 -executable -type f | sort -n`; do
    install $i
  done
fi
