#!/bin/bash

compile() {
  for i in inotify waitfor; do
    if [ ! -e bin/$i ]; then
      echo "Making $i"
      cc src/$i.c -o bin/$i
    fi
  done
}

install() {
  name=`basename $1`
  if [ ! -e $HOME/bin/$name ]; then
    echo "Installing $name"
    cp -pu $1 $HOME/bin
  else
    echo "Skipping $name (latest version installed)"
  fi
}

compile

cd bin
if [ $# -gt 0 ]; then
  while [ $# -gt 0 ]; do
    install $1
    shift
  done
else
  for i in `find -maxdepth 1 -executable -type f`; do
    install $i
  done
fi
