#!/bin/bash

compile() {
  for i in inotify waitfor; do
    if [ ! -e bin/$i ]; then
      echo "Making $i"
      cc src/$i.c -o bin/$i
    fi
  done
}

die() {
  echo $1
  exit
}

install() {
  name=`basename $1`
  install=0
  if [ "$2" == "force" ]; then
    install=1
  elif [ ! -e $HOME/bin/$name ]; then
    install=1
  else
    issame=`md5sum $HOME/bin/$name $1 | uniq -w 33 | wc -l`
    if [ $issame -eq "1" ]; then
      install=0
    else
      echo -n "Checksums for $name don't match. install it? (y/n/(d)iff) "
      read n
      case $n in
        y) install=1 ;;

        d) 
          diff -c $HOME/bin/$name $1
          install $1
          return
          ;;
      esac
      echo -n " ..."
    fi
  fi

  if [ $install -eq "1" ]; then
    [ -e $PWD/$1 ] || die "$1 does not exist"
    echo "Installing $name"
    [ -h $HOME/bin/$1 -o -e $HOME/bin/$1 ] && rm $HOME/bin/$1
    ln -s $PWD/$1 $HOME/bin
  else
    echo "Skipping $name"
  fi
}

compile

cd bin
if [ $# -gt 0 ]; then
  while [ $# -gt 0 ]; do
    install $1 force
    shift
  done
else
  for i in `find -maxdepth 1 -executable -type f | sort -n`; do
    install $i
  done
fi
