#!/bin/bash

bin/laptop.sh

for i in \
  apache2 avahi-daemon bluetooth      \
  cups docker hostapd isc-dhcp-server \
  libvirt-guests libvirtd mysql       \
  nfs-common postgresql rpcbind saned; do

  sudo service $i stop
done
for i in adb hostapd hamster; do
  echo killing $i
  sudo pkill $i
done
