#!/bin/bash

./laptop.sh

for i in  \
  avahi-daemon \
  bluetooth \
  cups cups-browsed saned \
  libvirt-guests libvirtd \
  mysql nginx apache2 \
  rpcbind nfs-common \
  isc-dhcp-server hostapd; do

  sudo service $i stop
done

for i in pulseaudio adb hostapd; do
  echo killing $i
  sudo pkill $i
done
