#!/bin/sh
echo Updating cscope ... please wait a long time
cscope -k -U -R -q -s .
echo Updating ctags ... please wait even longer
ctags \
  --language-force=php \
  -B --fields=+afikKlmnsSzt --extra=+fq --sort=foldcase -R  .
