#!/bin/sh
echo Updating cscope ... please wait a long time
cscope -R -b -q -s /usr/local/include/,/usr/include/,.
echo Updating ctags ... please wait even longer
ctags -B --c++-kinds=+p --fields=+afikKlmnsSzt --extra=+q --sort=foldcase -R /usr/local/include/ /usr/include .
