#!/bin/sh
# from http://stackoverflow.com/questions/4746523/using-tags-in-vim
echo Updating ctags ... please wait 

[ -e ~/.ctags ] && mv ~/.ctags ~/.ctags-backup

cat > ~/.ctags << END
--langdef=js
--langmap=js:.js
--regex-js=/([A-Za-z0-9._\$]+)[ \t]*[:=][ \t]*\{/\1/,object/
--regex-js=/([A-Za-z0-9._\$()]+)[ \t]*[:=][ \t]*function[ \t]*\(/\1/,function/
--regex-js=/function[ \t]+([A-Za-z0-9._\$]+)[ \t]*\(([^)])\)/\1/,function/
--regex-js=/([A-Za-z0-9._\$]+)[ \t]*[:=][ \t]*\[/\1/,array/
--regex-js=/([^= ]+)[ \t]*=[ \t]*[^"]'[^']*/\1/,string/
--regex-js=/([^= ]+)[ \t]*=[ \t]*[^']"[^"]*/\1/,string/
END

ctags-exuberant -h ".js" --exclude=".min.js" --sort=foldcase --totals=yes --tag-relative=yes --fields=+afikKlmnsSzt --extra=+ -R .

[ -e ~/.ctags-backup ] && mv ~/.ctags-backup ~/.ctags
